[workspace]
resolver = "2"
members = [
    "psoc4100s-pac",
    "psoc4100s-hal",
    "psoc4100s-examples",
]

[workspace.package]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/yodaldevoid/psoc4-rs"
